name: Python CI

on:
  push:
    branches:
      - main  # substitua 'main' pelo nome do seu branch principal
  pull_request:
    branches:
      - main  # substitua 'main' pelo nome do seu branch principal

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # substitua '3.x' pela versão do Python que você está usando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # ajuste conforme necessário

    - name: Run tests
      run: |
        python -m pytest  # ou o comando que você usa para executar seus testes

    - name: Generate coverage report
      run: |
        python -m pytest --cov-report html --cov=my_module tests/
      continue-on-error: true  # opcional, permite que o fluxo de trabalho continue mesmo se os testes falharem

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: htmlcov  # ajuste para o caminho correto do seu relatório de cobertura

