name: Python Package CI

on:
  push:
    branches:
      - main  # substitua 'main' pelo nome do seu branch principal
  pull_request:
    branches:
      - main  # substitua 'main' pelo nome do seu branch principal

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # substitua '3.x' pela versão do Python que você está usando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # ajuste conforme necessário
      working-directory: ${{ github.workspace }}

    - name: Build and publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install --upgrade setuptools wheel
        python setup.py sdist bdist_wheel
        python -m twine upload --repository pypi dist/*
